package com.vk.directop.odinintentexample.city

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.DividerItemDecoration
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.vk.directop.odinintentexample.R

class CityActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_city)

        val citiesList: List<City> = initList()

        val cityRecyclerView: RecyclerView = findViewById(R.id.city_recycler_view)
        cityRecyclerView.layoutManager = LinearLayoutManager(this, LinearLayoutManager.VERTICAL,false)
        cityRecyclerView.addItemDecoration(
            DividerItemDecoration(
                this,
                DividerItemDecoration.VERTICAL
            )
        )
        cityRecyclerView.adapter = CityAdapter(citiesList)


    }

    fun initList(): List<City> {
        return listOf(
            City("Москва", 12655),
            City("Санкт-Петербург", 5384),
            City("Новосибирск", 1620),
            City("Екатеринбург", 1495),
            City("Казань", 1257),
            City("Нижний Новгород", 1244),
            City("Челябинск", 1188),
            City("Самара", 1145),
            City("Омск", 1140),
            City("Ростов-на-Дону", 1138),
            City("Уфа", 1126),
            City("Красноярск", 1093),
            City("Воронеж", 1051),
            City("Пермь", 1049),
            City("Волгоград", 1005),
            City("Краснодар", 949),
            City("Саратов", 830),
            City("Тюмень", 817),
            City("Тольятти", 693),
            City("Ижевск", 646),
            City("Барнаул", 631),
            City("Ульяновск", 625),
            City("Иркутск", 618),
            City("Хабаровск", 610),
            City("Махачкала", 604),
            City("Ярославль", 601),
            City("Владивосток", 601),
            City("Оренбург", 573),
            City("Томск", 569),
            City("Кемерово", 553),
            City("Новокузнецк", 545),
            City("Рязань", 535),
            City("Набережные Челны", 532),
            City("Астрахань", 524),
            City("Киров", 521),
            City("Пенза", 516),
            City("Севастополь", 510),
            City("Балашиха[20]", 507),
            City("Липецк", 503),
            City("Чебоксары", 496),
            City("Калининград", 493),
            City("Тула", 468),
            City("Ставрополь", 455),
            City("Курск", 451),
            City("Улан-Удэ", 438),
            City("Сочи", 432),
            City("Тверь", 425),
            City("Магнитогорск", 413),
            City("Иваново", 402),
            City("Брянск", 400),
            City("Белгород", 392),
            City("Сургут", 387),
            City("Владимир", 352),
            City("Чита", 351),
            City("Архангельск", 345),
            City("Нижний Тагил", 345),
            City("Симферополь", 336),
            City("Калуга", 332),
            City("Якутск", 331),
            City("Грозный", 325),
            City("Волжский", 324),
            City("Смоленск", 320),
            City("Саранск", 317),
            City("Череповец", 312),
            City("Курган", 309),
            City("Подольск[21]", 309),
            City("Вологда", 309),
            City("Орёл", 304),
            City("Владикавказ", 302),
            City("Тамбов", 290),
            City("Мурманск", 283),
            City("Петрозаводск", 281),
            City("Нижневартовск", 279),
            City("Кострома", 277),
            City("Йошкар-Ола", 276),
            City("Новороссийск", 276),
            City("Стерлитамак", 274),
            City("Химки", 258),
            City("Таганрог", 248),
            City("Мытищи", 246),
            City("Сыктывкар", 244),
            City("Комсомольск-на-Амуре", 241),
            City("Нижнекамск", 240),
            City("Нальчик", 239),
            City("Шахты", 229),
            City("Дзержинск", 227),
            City("Энгельс", 226),
            City("Благовещенск", 226),
            City("Королёв[22]", 225),
            City("Братск", 225),
            City("Великий Новгород", 225),
            City("Орск", 225),
            City("Старый Оскол", 224),
            City("Ангарск", 223),
            City("Псков", 209),
            City("Люберцы", 208),
            City("Южно-Сахалинск", 200),
            City("Бийск", 198),
            City("Прокопьевск", 188),
            City("Абакан", 187),
            City("Армавир", 187),
            City("Балаково", 186),
            City("Норильск", 183),
            City("Рыбинск", 182),
            City("Северодвинск", 181),
            City("Петропавловск-Камчатский", 179),
            City("Красногорск", 176),
            City("Уссурийск", 173),
            City("Волгодонск", 170),
            City("Новочеркасск", 166),
            City("Сызрань", 165),
            City("Каменск-Уральский", 164),
            City("Златоуст", 162),
            City("Альметьевск", 158),
            City("Электросталь", 153),
            City("Керчь[Крым 1][19]", 152),
            City("Миасс", 151),
            City("Салават", 149),
            City("Хасавюрт", 146),
            City("Пятигорск", 146),
            City("Копейск", 146),
            City("Находка", 143),
            City("Рубцовск", 140),
            City("Майкоп", 139),
            City("Коломна", 139),
            City("Березники", 137),
            City("Одинцово", 136),
            City("Домодедово", 135),
            City("Ковров", 134),
            City("Нефтекамск", 132),
            City("Каспийск", 129),
            City("Нефтеюганск", 128),
            City("Кисловодск", 128),
            City("Новочебоксарск", 128),
            City("Батайск", 127),
            City("Щёлково", 127),
            City("Дербент", 127),
            City("Серпухов", 125),
            City("Назрань", 124),
            City("Раменское", 124),
            City("Черкесск", 123),
            City("Новомосковск", 122),
            City("Кызыл", 120),
            City("Первоуральск", 119),
            City("Новый Уренгой", 118),
            City("Орехово-Зуево", 118),
            City("Долгопрудный", 118),
            City("Обнинск", 116),
            City("Невинномысск", 116),
            City("Ессентуки", 115),
            City("Октябрьский", 114),
            City("Димитровград", 112),
            City("Пушкино", 109),
            City("Камышин", 109),
            City("Ноябрьск", 108),
            City("Евпатория", 108),
            City("Реутов", 108),
            City("Жуковский", 108),
            City("Северск", 106),
            City("Муром", 106),
            City("Новошахтинск", 105),
            City("Артём", 105),
            City("Ачинск", 105),
            City("Бердск", 104),
            City("Элиста", 104),
            City("Арзамас", 103),
            City("Ханты-Мансийск", 103),
            City("Ногинск", 103),
        )
    }
}

